In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression

In [2]:
dt = pd.read_csv('final_data.csv')

In [3]:
dt['city'] = LabelEncoder().fit_transform(dt.city_name)
dt['labels'] = LabelEncoder().fit_transform(dt.label)

In [4]:
dt = dt.drop(columns=['city_name','Unnamed: 0','Unnamed: 0.1'])

In [5]:
X = np.array(dt.drop(columns=['label','labels']))
y = np.array(dt.labels)

In [6]:
trainx, testx, trainy, testy = train_test_split(X, y, test_size=0.3)

In [8]:
%%time
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
clf = LogisticRegression(random_state=0, solver='lbfgs',max_iter =10,
                          multi_class='multinomial').fit(trainx,trainy)
                          
y_pred = clf.predict(testx)
print(confusion_matrix(testy,y_pred))  
print(classification_report(testy,y_pred))  
print(accuracy_score(testy, y_pred))  

/Users/zhili/miniconda3/envs/ml/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:757: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)


[[     0      0      0      0      0     20      0]
 [     0      0      0      0      0   1641     13]
 [     0      0      0      0      0   8110     86]
 [     0      0      0      0      0     83      0]
 [     0      0      0      0      0     41      0]
 [     0      0      0      0      0 139488    272]
 [     0      0      1      0      0  45176    388]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        20
           1       0.00      0.00      0.00      1654
           2       0.00      0.00      0.00      8196
           3       0.00      0.00      0.00        83
           4       0.00      0.00      0.00        41
           5       0.72      1.00      0.83    139760
           6       0.51      0.01      0.02     45565

   micro avg       0.72      0.72      0.72    195319
   macro avg       0.18      0.14      0.12    195319
weighted avg       0.63      0.72      0.60    195319

0.7161412868179747
CPU times: user 9.3

/Users/zhili/miniconda3/envs/ml/lib/python3.6/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [13]:
%%time
from sklearn.naive_bayes import GaussianNB
clf = GaussianNB().fit(trainx,trainy)
y_pred = clf.predict(testx)
print(confusion_matrix(testy,y_pred))  
print(classification_report(testy,y_pred))  
print(accuracy_score(testy, y_pred))  

[[    1     0     1     0    18     0     0]
 [  381    19   367   160   639    25    63]
 [ 2356    42   684   179  4066   403   466]
 [    7     0    25    23    24     1     3]
 [    0     0     0     0    40     1     0]
 [21443    31   277    40 94032 23028   909]
 [10867    79   806   177 23479  8258  1899]]
              precision    recall  f1-score   support

           0       0.00      0.05      0.00        20
           1       0.11      0.01      0.02      1654
           2       0.32      0.08      0.13      8196
           3       0.04      0.28      0.07        83
           4       0.00      0.98      0.00        41
           5       0.73      0.16      0.27    139760
           6       0.57      0.04      0.08     45565

   micro avg       0.13      0.13      0.13    195319
   macro avg       0.25      0.23      0.08    195319
weighted avg       0.67      0.13      0.22    195319

0.1315489020525397
CPU times: user 1.34 s, sys: 746 ms, total: 2.09 s
Wall time: 2.16 s