In [3]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier

In [4]:
dt = pd.read_csv('final_data.csv')

In [5]:
dt['city'] = LabelEncoder().fit_transform(dt.city_name)
dt['labels'] = LabelEncoder().fit_transform(dt.label)

In [6]:
dt = dt.drop(columns=['city_name','Unnamed: 0','Unnamed: 0.1'])

In [7]:
X = np.array(dt.drop(columns=['label','labels']))
y = np.array(dt.labels)

In [8]:
trainx, testx, trainy, testy = train_test_split(X, y, test_size=0.3)

### Random Forest with 10 trees

In [12]:
%%time
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
rf_10 = RandomForestClassifier(n_estimators=10, max_depth=20).fit(trainx, trainy)
y_pred = rf_10.predict(testx)
print(confusion_matrix(testy,y_pred))  
print(classification_report(testy,y_pred))  
print(accuracy_score(testy, y_pred))  

[[     0      0      0      0      0     12      8]
 [     0    385    754      2      0     91    411]
 [     0    249   2619      5      1    563   4735]
 [     0     39     29      2      0     13     17]
 [     0      0      1      0      2     38      4]
 [     0     17    319      0      1 128400  10867]
 [     1     98   1947      1      0  15884  27804]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        20
           1       0.49      0.23      0.32      1643
           2       0.46      0.32      0.38      8172
           3       0.20      0.02      0.04       100
           4       0.50      0.04      0.08        45
           5       0.89      0.92      0.90    139604
           6       0.63      0.61      0.62     45735

   micro avg       0.82      0.82      0.82    195319
   macro avg       0.45      0.31      0.33    195319
weighted avg       0.81      0.82      0.81    195319

0.8151383121969701
CPU times: user 23.

### Random Forest with 100 trees

In [13]:
%%time
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
rf_100 = RandomForestClassifier(n_estimators=100, max_depth=20).fit(trainx, trainy)
y_pred = rf_100.predict(testx)
print(confusion_matrix(testy,y_pred))  
print(classification_report(testy,y_pred))  
print(accuracy_score(testy, y_pred))  

[[     0      0      0      0      0     14      6]
 [     0    353    821      2      0     68    399]
 [     0    201   2628      3      0    486   4854]
 [     0     41     30      1      0     10     18]
 [     0      0      0      0      1     38      6]
 [     0     11    238      0      3 128860  10492]
 [     0     74   1582      0      0  15209  28870]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        20
           1       0.52      0.21      0.30      1643
           2       0.50      0.32      0.39      8172
           3       0.17      0.01      0.02       100
           4       0.25      0.02      0.04        45
           5       0.89      0.92      0.91    139604
           6       0.65      0.63      0.64     45735

   micro avg       0.82      0.82      0.82    195319
   macro avg       0.42      0.30      0.33    195319
weighted avg       0.81      0.82      0.82    195319

0.8228231764446879
CPU times: user 3mi

/Users/zhili/miniconda3/envs/ml/lib/python3.6/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


### Random Forest with 500 trees

In [15]:
%%time
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
rf_100 = RandomForestClassifier(n_estimators=500, max_depth=20).fit(trainx, trainy)
y_pred = rf_100.predict(testx)
print(confusion_matrix(testy,y_pred))  
print(classification_report(testy,y_pred))  
print(accuracy_score(testy, y_pred)) 

[[     0      0      0      0      0     14      6]
 [     0    361    826      1      0     70    385]
 [     0    194   2666      2      1    477   4832]
 [     0     43     30      0      0     11     16]
 [     0      0      0      0      1     38      6]
 [     0     10    235      0      1 128999  10359]
 [     0     71   1553      0      0  15127  28984]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        20
           1       0.53      0.22      0.31      1643
           2       0.50      0.33      0.40      8172
           3       0.00      0.00      0.00       100
           4       0.33      0.02      0.04        45
           5       0.89      0.92      0.91    139604
           6       0.65      0.63      0.64     45735

   micro avg       0.82      0.82      0.82    195319
   macro avg       0.42      0.30      0.33    195319
weighted avg       0.81      0.82      0.82    195319

0.8243488856690849
CPU times: user 19m

/Users/zhili/miniconda3/envs/ml/lib/python3.6/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
